spring:
  application:
    name: third-party
  gulimall:
    sms:
      host: "http://dingxin.market.alicloudapi.com"
      path: "/dx/sendSms"
      method: 'POST'
      appcode: "7343907f98834a15a54068a4da9a2e04"





